Update external-images CI pull to skip pulling images locally existing
inviqa/harness-go pull request #67
Opened 2020-11-10 18:05 UTC by andytson-inviqa

This assumes the CI environment is clear of local docker images each day to ensure at least daily updates

2020-11-11 13:35 UTC, jameshalsall approved these changes

2020-11-27 10:04 UTC, kierenevans requested changes
Fix for local running

2020-11-27 10:04 UTC, kierenevans commented on harness/config/external-images.yml
> +command('external-images config --skip-exists'):
```suggestion
command('external-images config [--skip-exists]'):
```
To fix issues running locally

2020-11-27 10:08 UTC, kierenevans approved these changes

2020-12-07 17:50 UTC, merged